import 'package:flutter/material.dart';import 'package:nurhossen_s_application5/core/app_export.dart';import 'package:nurhossen_s_application5/presentation/set_order_with_single_page/set_order_with_single_page.dart';import 'package:nurhossen_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:nurhossen_s_application5/widgets/app_bar/appbar_subtitle.dart';import 'package:nurhossen_s_application5/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:nurhossen_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:nurhossen_s_application5/widgets/custom_bottom_bar.dart';
// ignore_for_file: must_be_immutable
class RevenueDetailsScreen extends StatelessWidget {RevenueDetailsScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 21.h, vertical: 20.v), child: Column(children: [_buildDataIsCounted(context), SizedBox(height: 28.v), _buildSixtyOne(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 43.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 19.h, top: 27.v, bottom: 22.v), onTap: () {onTapArrowLeft(context);}), title: AppbarSubtitle(text: "Revenue Details", margin: EdgeInsets.only(left: 20.h)), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgSend, margin: EdgeInsets.fromLTRB(21.h, 24.v, 21.h, 19.v))], styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildDataIsCounted(BuildContext context) { return SizedBox(height: 175.v, width: 348.h, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 33.h, vertical: 13.v), decoration: AppDecoration.fillBlack.copyWith(borderRadius: BorderRadiusStyle.roundedBorder7), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 41.h), child: Text("Data is counted by every hour", style: CustomTextStyles.bodySmallOnPrimary)), SizedBox(height: 7.v), RichText(text: TextSpan(children: [TextSpan(text: "Daily Statistics based on", style: CustomTextStyles.bodySmallOnPrimary_1), TextSpan(text: " USA time (UTC+8)", style: CustomTextStyles.labelLargeOnPrimary)]), textAlign: TextAlign.left), SizedBox(height: 42.v)]))), Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.symmetric(horizontal: 16.h), padding: EdgeInsets.symmetric(horizontal: 13.h, vertical: 14.v), decoration: AppDecoration.fillAmberA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder7), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 2.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("Total Profit Today (USDT)", style: CustomTextStyles.labelMediumOnPrimary), Text("Cumulative Profit (USDT)", style: CustomTextStyles.labelMediumOnPrimary)])), SizedBox(height: 10.v), Padding(padding: EdgeInsets.only(left: 2.h, right: 46.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("23.456758", style: CustomTextStyles.labelLargeOnPrimarySemiBold), Text("23.45906758", style: CustomTextStyles.labelLargeOnPrimarySemiBold)])), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 2.h, right: 77.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("~ 34.1 USD", style: CustomTextStyles.labelMediumOnPrimary), Text("~ 14.1 USD", style: CustomTextStyles.labelMediumOnPrimary)]))])))])); } 
/// Section Widget
Widget _buildSixtyOne(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 21.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder7), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildFortySix(context, dynamicText: "12-07-23", dynamicText1: "39.6758934", dynamicText2: "Profit"), SizedBox(height: 17.v), _buildFortySix(context, dynamicText: "12-07-23", dynamicText1: "39.6758934", dynamicText2: "Profit"), SizedBox(height: 17.v), _buildFortySix(context, dynamicText: "12-07-23", dynamicText1: "39.6758934", dynamicText2: "Profit"), SizedBox(height: 17.v), _buildFortySix(context, dynamicText: "12-07-23", dynamicText1: "39.6758934", dynamicText2: "Profit")])); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
/// Common widget
Widget _buildFortySix(BuildContext context, {required String dynamicText, required String dynamicText1, required String dynamicText2, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 9.v), decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder7), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 7.v, bottom: 10.v), child: Text(dynamicText, style: CustomTextStyles.bodySmallAmberA700.copyWith(color: appTheme.amberA700))), Spacer(flex: 36), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(dynamicText1, style: CustomTextStyles.labelLargeAmberA700.copyWith(color: appTheme.amberA700)), Text(dynamicText2, style: CustomTextStyles.bodySmallLight10.copyWith(color: appTheme.black900))]), Spacer(flex: 63), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 10.v, width: 6.h, margin: EdgeInsets.symmetric(vertical: 12.v))])); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Group6: return AppRoutes.setOrderWithSinglePage; case BottomBarEnum.Frameonprimary: return "/"; case BottomBarEnum.User: return "/"; case BottomBarEnum.Group1101: return "/"; case BottomBarEnum.Group9: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.setOrderWithSinglePage: return SetOrderWithSinglePage(); default: return DefaultWidget();} } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
