import 'package:flutter/material.dart';import 'package:nurhossen_s_application5/core/app_export.dart';import 'package:nurhossen_s_application5/widgets/custom_elevated_button.dart';import 'package:nurhossen_s_application5/widgets/custom_icon_button.dart';import 'package:nurhossen_s_application5/widgets/custom_outlined_button.dart';class KnowMoreAboutXpertbitScreen extends StatelessWidget {const KnowMoreAboutXpertbitScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 37.h, vertical: 34.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildWhatIsAutoTradeSection(context, dynamicText: "What is Xpertbit?"), SizedBox(height: 14.v), _buildWhatIsAutoTradeSection(context, dynamicText: "What is auto trade?"), Spacer(), CustomElevatedButton(height: 60.v, text: "Log in", margin: EdgeInsets.only(left: 32.h, right: 44.h), buttonStyle: CustomButtonStyles.fillAmberA, buttonTextStyle: CustomTextStyles.headlineLargeMedium, onPressed: () {onTapLogIn(context);}), SizedBox(height: 20.v), CustomOutlinedButton(height: 60.v, text: "Sign up", margin: EdgeInsets.only(left: 32.h, right: 44.h), buttonStyle: CustomButtonStyles.outlineAmberA, buttonTextStyle: CustomTextStyles.headlineLargeAmberA700, onPressed: () {onTapSignUp(context);}), SizedBox(height: 54.v)])))); } 
/// Common widget
Widget _buildWhatIsAutoTradeSection(BuildContext context, {required String dynamicText, }) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(dynamicText, style: CustomTextStyles.titleLargeBlack900Medium.copyWith(color: appTheme.black900)), SizedBox(height: 1.v), Container(padding: EdgeInsets.symmetric(horizontal: 126.h, vertical: 38.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: CustomIconButton(height: 64.adaptSize, width: 64.adaptSize, padding: EdgeInsets.all(11.h), child: CustomImageView(imagePath: ImageConstant.imgTelevision)))]); } 
/// Navigates to the logInOneScreen when the action is triggered.
onTapLogIn(BuildContext context) { Navigator.pushNamed(context, AppRoutes.logInOneScreen); } 
/// Navigates to the signUpScreen when the action is triggered.
onTapSignUp(BuildContext context) { Navigator.pushNamed(context, AppRoutes.signUpScreen); } 
 }
