import 'package:flutter/material.dart';import 'package:nurhossen_s_application5/core/app_export.dart';import 'package:nurhossen_s_application5/presentation/set_order_with_single_page/set_order_with_single_page.dart';import 'package:nurhossen_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:nurhossen_s_application5/widgets/app_bar/appbar_subtitle_five.dart';import 'package:nurhossen_s_application5/widgets/app_bar/appbar_subtitle_four.dart';import 'package:nurhossen_s_application5/widgets/app_bar/appbar_trailing_image.dart';import 'package:nurhossen_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:nurhossen_s_application5/widgets/custom_bottom_bar.dart';import 'package:nurhossen_s_application5/widgets/custom_radio_button.dart';
// ignore_for_file: must_be_immutable
class PollScreen extends StatelessWidget {PollScreen({Key? key}) : super(key: key);

String radioGroup = "";

List<String> radioList = ["lbl_btc2", "lbl_usdt2", "lbl_max"];

String radioGroup1 = "";

List<String> radioList1 = ["lbl_btc2", "lbl_usdt2", "lbl_max"];

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 44.h, vertical: 20.v), child: Column(children: [_buildWhatIsYourFavourite(context), SizedBox(height: 20.v), _buildBtcRadioGroup(context), SizedBox(height: 20.v), _buildBtcRadioGroup1(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h, top: 26.v, bottom: 23.v), onTap: () {onTapArrowLeft(context);}), title: Padding(padding: EdgeInsets.only(left: 11.h, top: 48.v, bottom: 6.v), child: Row(children: [AppbarSubtitleFive(text: "Signals", margin: EdgeInsets.only(top: 1.v)), AppbarSubtitleFive(text: "Orders", margin: EdgeInsets.only(left: 20.h, bottom: 1.v))])), actions: [Padding(padding: EdgeInsets.only(top: 48.v), child: Column(children: [Row(children: [AppbarSubtitleFour(text: "Results"), AppbarSubtitleFour(text: "News", margin: EdgeInsets.only(left: 20.h)), AppbarSubtitleFour(text: "Poll", margin: EdgeInsets.only(left: 20.h)), AppbarSubtitleFour(text: "Chat", margin: EdgeInsets.only(left: 20.h))]), SizedBox(height: 3.v), AppbarTrailingImage(imagePath: ImageConstant.imgRectangle142, margin: EdgeInsets.only(left: 121.h, right: 43.h))]))], styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildWhatIsYourFavourite(BuildContext context) { return Container(width: 301.h, margin: EdgeInsets.only(right: 1.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 17.v), decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.roundedBorder7), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("What is your Favourite Crypto?", style: theme.textTheme.bodyLarge), SizedBox(height: 20.v), Padding(padding: EdgeInsets.only(left: 11.h), child: Row(children: [Container(height: 15.adaptSize, width: 15.adaptSize, margin: EdgeInsets.only(top: 3.v), decoration: BoxDecoration(color: appTheme.black900.withOpacity(0.2), borderRadius: BorderRadius.circular(7.h))), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("BTC", style: theme.textTheme.labelLarge))])), SizedBox(height: 25.v), Padding(padding: EdgeInsets.only(left: 11.h), child: Row(children: [Container(height: 15.adaptSize, width: 15.adaptSize, margin: EdgeInsets.only(top: 2.v), decoration: BoxDecoration(color: appTheme.blueGray10001, borderRadius: BorderRadius.circular(7.h))), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("USDT", style: theme.textTheme.labelLarge))])), SizedBox(height: 26.v), Padding(padding: EdgeInsets.only(left: 11.h), child: Row(children: [Container(height: 15.adaptSize, width: 15.adaptSize, margin: EdgeInsets.symmetric(vertical: 1.v), decoration: BoxDecoration(color: appTheme.black900.withOpacity(0.2), borderRadius: BorderRadius.circular(7.h))), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("Max", style: theme.textTheme.labelLarge))])), SizedBox(height: 8.v)])); } 
/// Section Widget
Widget _buildBtcRadioGroup(BuildContext context) { return Container(margin: EdgeInsets.only(right: 1.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 17.v), decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.roundedBorder7), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("What is your Favourite Crypto?", style: theme.textTheme.bodyLarge), SizedBox(height: 20.v), Padding(padding: EdgeInsets.only(left: 11.h, right: 192.h), child: Column(children: [Padding(padding: EdgeInsets.only(right: 7.h), child: CustomRadioButton(text: "BTC", value: radioList[0], groupValue: radioGroup, textStyle: theme.textTheme.labelLarge, onChange: (value) {radioGroup = value;})), Padding(padding: EdgeInsets.only(top: 25.v), child: CustomRadioButton(text: "USDT", value: radioList[1], groupValue: radioGroup, textStyle: theme.textTheme.labelLarge, onChange: (value) {radioGroup = value;})), Padding(padding: EdgeInsets.only(top: 26.v, right: 6.h), child: CustomRadioButton(text: "Max", value: radioList[2], groupValue: radioGroup, textStyle: theme.textTheme.labelLarge, onChange: (value) {radioGroup = value;}))])), SizedBox(height: 8.v)])); } 
/// Section Widget
Widget _buildBtcRadioGroup1(BuildContext context) { return Container(margin: EdgeInsets.only(right: 1.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 17.v), decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.roundedBorder7), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("What is your Favourite Crypto?", style: theme.textTheme.bodyLarge), SizedBox(height: 20.v), Padding(padding: EdgeInsets.only(left: 11.h, right: 192.h), child: Column(children: [Padding(padding: EdgeInsets.only(right: 7.h), child: CustomRadioButton(text: "BTC", value: radioList1[0], groupValue: radioGroup1, textStyle: theme.textTheme.labelLarge, onChange: (value) {radioGroup1 = value;})), Padding(padding: EdgeInsets.only(top: 25.v), child: CustomRadioButton(text: "USDT", value: radioList1[1], groupValue: radioGroup1, textStyle: theme.textTheme.labelLarge, onChange: (value) {radioGroup1 = value;})), Padding(padding: EdgeInsets.only(top: 26.v, right: 6.h), child: CustomRadioButton(text: "Max", value: radioList1[2], groupValue: radioGroup1, textStyle: theme.textTheme.labelLarge, onChange: (value) {radioGroup1 = value;}))])), SizedBox(height: 8.v)])); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Group6: return AppRoutes.setOrderWithSinglePage; case BottomBarEnum.Frameonprimary: return "/"; case BottomBarEnum.User: return "/"; case BottomBarEnum.Group1101: return "/"; case BottomBarEnum.Group9: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.setOrderWithSinglePage: return SetOrderWithSinglePage(); default: return DefaultWidget();} } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
