import '../home_to_profile_screen/widgets/userprofilelist_item_widget.dart';import 'package:flutter/material.dart';import 'package:nurhossen_s_application5/core/app_export.dart';import 'package:nurhossen_s_application5/presentation/set_order_with_single_page/set_order_with_single_page.dart';import 'package:nurhossen_s_application5/widgets/app_bar/appbar_circleimage.dart';import 'package:nurhossen_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:nurhossen_s_application5/widgets/app_bar/appbar_subtitle_one.dart';import 'package:nurhossen_s_application5/widgets/app_bar/appbar_subtitle_three.dart';import 'package:nurhossen_s_application5/widgets/app_bar/appbar_subtitle_two.dart';import 'package:nurhossen_s_application5/widgets/app_bar/appbar_title_image.dart';import 'package:nurhossen_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:nurhossen_s_application5/widgets/custom_bottom_bar.dart';
// ignore_for_file: must_be_immutable
class HomeToProfileScreen extends StatelessWidget {HomeToProfileScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 20.v), _buildUserProfileList(context)])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 116.v, leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h, top: 48.v, bottom: 44.v), onTap: () {onTapArrowLeft(context);}), title: Padding(padding: EdgeInsets.only(left: 6.h), child: Column(children: [Row(children: [Container(padding: EdgeInsets.all(3.h), decoration: AppDecoration.outlineOnPrimary.copyWith(borderRadius: BorderRadiusStyle.circleBorder42), child: Column(children: [SizedBox(height: 1.v), AppbarCircleimage(imagePath: ImageConstant.imgFrontViewYoun2, margin: EdgeInsets.only(right: 1.h))])), Padding(padding: EdgeInsets.only(left: 12.h, top: 3.v), child: Column(children: [Padding(padding: EdgeInsets.only(right: 71.h), child: Row(children: [AppbarSubtitleOne(text: "Abir Ahmed", margin: EdgeInsets.only(top: 11.v)), AppbarTitleImage(imagePath: ImageConstant.imgFrameLightBlue500, margin: EdgeInsets.only(bottom: 17.v))])), SizedBox(height: 4.v), Row(children: [AppbarSubtitleThree(text: "1.5k follower", margin: EdgeInsets.only(bottom: 11.v)), Container(height: 28.070007.v, width: 99.h, margin: EdgeInsets.only(left: 37.h, top: 3.v), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Container(height: 28.v, width: 99.h, decoration: BoxDecoration(color: theme.colorScheme.onPrimary, borderRadius: BorderRadius.circular(14.h), border: Border.all(color: theme.colorScheme.onPrimary, width: 1.h)))), AppbarSubtitleTwo(text: "Following", margin: EdgeInsets.only(left: 12.h, top: 4.v, right: 12.h))]))])]))])])), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildUserProfileList(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 20.v);}, itemCount: 3, itemBuilder: (context, index) {return UserprofilelistItemWidget();}))); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Group6: return AppRoutes.setOrderWithSinglePage; case BottomBarEnum.Frameonprimary: return "/"; case BottomBarEnum.User: return "/"; case BottomBarEnum.Group1101: return "/"; case BottomBarEnum.Group9: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.setOrderWithSinglePage: return SetOrderWithSinglePage(); default: return DefaultWidget();} } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
